### PR TITLE
[DEV-1609] add refund fx

### PR DESCRIPTION
**Pull request by waynehoover**

### CODE REVIEW

**Review by jonathandiep — APPROVED** [review]

**Comment by jonathandiep** [comment]
Check failed tests

IERC20 doesn't exist in Quest.sol

**Comment by waynehoover** [comment]
> Check failed tests
> 
> IERC20 doesn't exist in Quest.sol

I added it and still fails, not sure why.

**Comment by jonathandiep** [comment]
> > Check failed tests
> > IERC20 doesn't exist in Quest.sol
> 
> I added it and still fails, not sure why.

safeTransfer only exists for SafeERC20 (not IERC20!)

**Comment by waynehoover** [comment]
> > > Check failed tests
> > > IERC20 doesn't exist in Quest.sol
> > 
> > 
> > I added it and still fails, not sure why.
> 
> safeTransfer only exists for SafeERC20 (not IERC20!)

I thought so to, but `SafeERC20(erc20Address_).safeTransfer(msg.sender, erc20Balance);` still won't compile.

**Pull request merged**
